'on': pull_request
name: Run tests
jobs:
  tests:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - 'platform=iOS Simulator,OS=13.4.1,name=iPhone 11'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Force xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
      - name: Install Bundle
        run: bundle install
      - name: Build and Test
        run: bundle exec fastlane ios tests
        env:
          destination: '${{ matrix.destination }}'
